const express = require('express');
const app = express();
const port = process.env.PORT || 3000;

app.get('/', (req, res) => {
  res.send('Hello, World!');
});

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
{
  "name": "my-app",
  "version": "1.0.0",
  "description": "A simple web application",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "express": "^4.17.1"
  },
  "engines": {
    "node": "14.x"
  }
}

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests (optional, can be skipped if no tests)
    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Heroku
      uses: akshnz/heroku-deploy@v1.3.2
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "your-app-name"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
git add .github/workflows/ci-cd-pipeline.yml
git commit -m "Set up CI/CD pipeline with Heroku deployment"
git push origin main
